### ISSUE TITLE
pip install -r requirements.txt fails

### ISSUE THREAD

**Issue by viren-vii** [csev/dj4e-samples#27]
This command fails and shows an error for `mysqlclient>=1.4.6`. It said `mysql-config` not found.
I resolved this by first installing `mysql-config` using `sudo apt-get install libmysqlclient-dev`.
Now it is working. 
The issue is solved but I would like to see this as a note on the website!
Thank you.

**Comment by csev** [comment]
Thanks - I updated the documentation and added a note to requirements.txt - it is not really needed for the samples code anyways.

**Comment by viren-vii** [comment]
I am following youtube tutorial! There I found out 
`https://dj4e.com/lectures/DJ-04-Model-One.txt` has contents of `https://www.dj4e.com/lectures/DJ-02-Model-Single.txt`
can I even state those issues here?

**Comment by csev** [comment]
Yes - feel free to make any comment on the content of DJ4E here as this is where I fix them.  In this particular situation, the file is there twice - on purpose because some ago I reorganized the course and those 01 02 03 ... numbers were changed - but the TXT files were in some video lectures and I had to keep both of the names with identical content.  Thanks.

**Comment by viren-vii** [comment]
Okay!
DJ4E is amazing. I had completed Web development for everybody specialization a year ago. I love your courses. Thank you! :D
