### ISSUE TITLE
ModuleNotFoundError: No module named 'tracks'. I pulled the code from Github but I keep getting the error in the "tracks " app that there is no module named "tracks". The folder doesn't even come with a manage.py file. Please any help will be appreciated.

### ISSUE THREAD

**Issue by Chibueze864** [csev/dj4e-samples#37]
ModuleNotFoundError: No module named 'tracks'. I pulled the code from Github but I keep getting the error in the "tracks " app that there is no module named "tracks". The folder doesn't even come with a manage.py file. Please any help will be appreciated.

**Comment by csev** [comment]
Tracks is not a Django project - dj4e-samples is one Django project and tracks is an application.   There is only one manage.py file.

**Comment by Chibueze864** [comment]
So 

> Tracks is not a Django project - dj4e-samples is one Django project and tracks is an application. There is only one manage.py file.

So please how do I use that manage.py for the tracks application? In your tutorial, you have a manage.py file in your tracks folder.

**Comment by csev** [comment]
Where do I have a manage.py in a tracks folder?   That would mean that tracks is a project and not an application.  If you could point to where you are seeing this, it would help.

**Comment by MarkusEicher** [comment]
Hi Chuck. I was a bit disturbed too. In the long form video under the freeCodeCamp playlist (18 hours version) you use a manage.py inside the tracks folder, but it is not present on the course material here. I post the link with the timestamp at around 5.05 here. There is also a folder named tracksmodel in the clip which is also missing in the repo. Just before going through this part in the video you present the model of the track and mention, that we built this in the lecture, but this was not the case and I follow the course on python4everywhere since the beginning. For me it is no problem, I can get around and I enjoy your teaching style and the course. But it might help some other students that are irritated when watching the freeCodeCamp version. Have a good time and thanks for the course.

https://youtu.be/o0XbHvKxw7Y?si=jR9DIgTzEopPHEMB&t=18292
